# Generated by Django 2.1.7 on 2019-02-28 00:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_remove_produto_tipoproduto2'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensOferta',
            fields=[
                ('idIntensOferta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('idOferta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=40)),
                ('data_inicio', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('data_fim', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='intensoferta',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.Oferta'),
        ),
        migrations.AddField(
            model_name='intensoferta',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
        ),
    ]
