# Generated by Django 2.1.7 on 2019-03-18 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='oferta',
            name='datafim',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 9, 28, 163395)),
        ),
        migrations.AddField(
            model_name='oferta',
            name='datainicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 9, 28, 162392)),
        ),
    ]
