# Generated by Django 2.1.7 on 2019-03-18 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20190317_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='datafim',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 10, 27, 238358)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='datainicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 10, 27, 238358)),
        ),
    ]
