# Generated by Django 2.1.7 on 2019-03-18 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20190317_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='datafim',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 21, 53, 287391)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='datainicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 21, 53, 287391)),
        ),
    ]
