# Generated by Django 2.1.7 on 2019-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descricaoimportcao', models.CharField(max_length=50)),
                ('descricaoexibicao', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipoproduto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tvs',
            fields=[
                ('idTv', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
    ]
