# Generated by Django 2.1.7 on 2019-02-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipoproduto2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
