# Generated by Django 2.1.7 on 2019-03-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_tipoproduto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.FileField(default=1, upload_to='media/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
