# Generated by Django 2.1.7 on 2019-03-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20190303_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
