# Generated by Django 2.1.7 on 2019-03-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='video',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
