# Generated by Django 2.1.7 on 2019-02-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tvs', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensTela',
            fields=[
                ('idIntensTela', models.AutoField(primary_key=True, serialize=False)),
                ('ordem', models.CharField(max_length=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('idTela', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('tempoexibicao', models.CharField(max_length=45)),
                ('video', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=10)),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvs.Tv')),
            ],
        ),
        migrations.AddField(
            model_name='intenstela',
            name='tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas.Tela'),
        ),
    ]
