# Generated by Django 2.1.7 on 2019-03-18 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20190317_2009'),
        ('telas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ofertas.Oferta'),
        ),
        migrations.AlterField(
            model_name='tela',
            name='tipo',
            field=models.CharField(choices=[('', 'Selecione'), ('oferta', 'Oferta'), ('tabela', 'Tabela'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tela',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
