# Generated by Django 2.1.7 on 2019-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('idTv', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
    ]
