# Generated by Django 2.1.7 on 2019-03-17 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='statuss',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 19, 53, 10, 138361)),
        ),
    ]
