# Generated by Django 2.1.7 on 2019-03-17 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0002_tv_statuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='statuss',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 19, 56, 7, 529908)),
        ),
    ]
