# Generated by Django 2.1.7 on 2019-03-17 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0003_auto_20190317_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='statuss',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 19, 57, 43, 370388)),
        ),
    ]
