# Generated by Django 2.1.7 on 2019-03-18 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0004_auto_20190317_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='statuss',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 0, 50, 307679)),
        ),
    ]
