# Generated by Django 2.1.7 on 2019-03-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0005_auto_20190317_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv',
            name='statuss',
        ),
    ]
