# Generated by Django 2.1.7 on 2019-03-18 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0006_remove_tv_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='statuss',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 10, 27, 235361)),
        ),
    ]
