# Generated by Django 2.1.7 on 2019-03-18 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0007_tv_statuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv',
            name='statuss',
        ),
        migrations.AddField(
            model_name='tv',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 20, 21, 53, 284395)),
        ),
    ]
