# Generated by Django 2.1.7 on 2019-04-07 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0008_auto_20190317_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='status',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 7, 15, 48, 24, 510556)),
        ),
    ]
